services:
  api:
    build:
      context: ..
      dockerfile: infra/.dev.api.dockerfile
    container_name: backend_api
    ports:
      - "3000:3000"
    volumes:
      - ..:/app
    env_file:
      - ../internal/shared/config/.env

    depends_on:
      redis:
        condition: service_healthy
      database:
        condition: service_healthy
      nats:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    networks:
      - app-network

  worker:
    build:
      context: ..
      dockerfile: infra/.dev.worker.dockerfile
    container_name: infra-layer
    env_file:
      - ../internal/shared/config/.env
    volumes:
      - ..:/app
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 4G
    # volumes:
    #   - transcoder_tmp:/tmp/transcoding

    depends_on:
      redis:
        condition: service_healthy
      database:
        condition: service_healthy
      nats:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    networks:
      - app-network
  redis:
    image: redis:latest
    command: ["redis-server", "--port", "6377", "--appendonly", "yes"]
    ports:
      - "6377:6377"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6377", "ping"] # 👈 Added -p 6377 here
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network

  nats:
    image: nats:2.12-alpine
    container_name: nats
    command: ["-js", "-sd", "/data", "-m", "8222"]
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats-data:/data
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8222/healthz || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - app-network

  clickhouse:
    image: clickhouse/clickhouse-server:25.8
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: analytics
      CLICKHOUSE_USER: analytics_user
      CLICKHOUSE_PASSWORD: analytics_password
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-logs:/var/log/clickhouse-server
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - app-network

  database:
    image: postgres:16
    container_name: pgdata
    restart: always

    ports:
      # - "5432:5432"
      - "5434:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db

    volumes:
      - pgdata:/var/lib/postgressql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  transcoder_tmp:
  redis-data:
  nats-data:
  clickhouse-data:
  clickhouse-logs:
