FROM python:3.11-slim

RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# copy requirements first
COPY requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir

# copy code after
COPY . .

CMD ["python", "main.py"]